#!/usr/bin/env bash
#
# Renders the demo tapes in demos/tapes/ to assets/demos/ with VHS, then
# losslessly optimizes every GIF with gifsicle.
#
#   ./demos/capture.sh                 # render everything
#   ./demos/capture.sh searchable      # render only tapes matching a name
#
# Requires: vhs (brew install vhs), gifsicle (brew install gifsicle).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TAPE_DIR="$REPO_ROOT/demos/tapes"
OUT_DIR="$REPO_ROOT/assets/demos"

# Minimum Node the package supports (package.json "engines").
MIN_NODE_MAJOR=22
MIN_NODE_MINOR=20

command -v vhs >/dev/null || { echo "error: vhs not found — brew install vhs" >&2; exit 1; }

# --- Resolve a Node that satisfies the engines floor ---------------------------
# VHS spawns a clean login shell whose PATH may resolve to an older Node than the
# package supports, so we pin an explicit bin directory and inject it into the tape.
node_ok() {
  local bin="${1:-}" ver major minor
  [ -n "$bin" ] && [ -x "$bin" ] || return 1
  ver="$("$bin" --version 2>/dev/null)" || return 1
  ver="${ver#v}"
  major="${ver%%.*}"
  minor="${ver#*.}"; minor="${minor%%.*}"
  [ "$major" -gt "$MIN_NODE_MAJOR" ] && return 0
  [ "$major" -eq "$MIN_NODE_MAJOR" ] && [ "$minor" -ge "$MIN_NODE_MINOR" ]
}

NODE_BIN=""
if node_ok "$(command -v node || true)"; then
  NODE_BIN="$(dirname "$(command -v node)")"
else
  # Fall back to the newest satisfying nvm install.
  while IFS= read -r candidate; do
    if node_ok "$candidate"; then NODE_BIN="$(dirname "$candidate")"; break; fi
  done < <(ls -d "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | sort -Vr)
fi

if [ -z "$NODE_BIN" ]; then
  echo "error: no Node >= ${MIN_NODE_MAJOR}.${MIN_NODE_MINOR} found (needed to run the examples)" >&2
  exit 1
fi

echo "▸ node:   $NODE_BIN ($("$NODE_BIN/node" --version))"
echo "▸ output: $OUT_DIR"
mkdir -p "$OUT_DIR"

# VHS resolves `Output`, `Screenshot` and `Source` against the working directory,
# and `Screenshot` only accepts a bare filename — so render inside a staging dir
# and copy the finished artifacts out. This also keeps half-rendered files from
# ever landing in the committed assets directory.
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# --- Generate the shared setup tape -------------------------------------------
# Every tape `Source`s this: the look (identical across captures, so the set is
# visually consistent) plus a bootstrap that puts the right Node on PATH and
# defines the `demo` helper the tapes launch with.
#
# `demo <name>` runs the command documented in examples/README.md:
#   node --no-warnings --loader ts-node/esm examples/<name>.tsx
# `--no-warnings` only suppresses Node's own loader/deprecation notices, which
# would otherwise cover the component in every frame.
#
# It first switches the terminal to its alternate screen buffer (`\033[?1049h`),
# the same thing vim and less do. The shell prompt and the echoed `demo …`
# command stay behind on the primary buffer, so the recording shows nothing but
# the component. It deliberately never switches back: restoring the primary
# buffer on exit would replace the final frame with a shell prompt.
#
# Nothing is recorded until a tape calls `Show`, which each does *after* the app
# has booted — so every capture opens on a fully rendered component.
cat > "$STAGE/.setup.tape" <<TAPE
# GENERATED by demos/capture.sh — do not edit; edit capture.sh instead.
Set FontSize 20
Set Padding 20
Set Theme "Catppuccin Mocha"
Set CursorBlink false
Set TypingSpeed 90ms
Set Framerate 24

Hide
Type "export PATH=$NODE_BIN:\$PATH" Enter
Type "cd $REPO_ROOT" Enter
Type "demo() { printf '\033[?1049h'; node --no-warnings --loader ts-node/esm examples/\$1.tsx; }" Enter
Type "clear" Enter
TAPE

# --- Render --------------------------------------------------------------------
# Back-to-back VHS runs occasionally come up with a wedged terminal. The tape is
# reported as executed either way, but the recording freezes: a `Screenshot`
# writes nothing at all, and a GIF comes out as hundreds of identical frames.
# Both are silent, so verify what each tape produced and retry rather than
# shipping a dead capture.
expected_artifacts() {
  # Published artifacts a tape declares: Output "<name>" and Screenshot <name>,
  # minus the `_`-prefixed throwaways.
  sed -nE 's/^[[:space:]]*Output[[:space:]]+"?([^"]+)"?[[:space:]]*$/\1/p;
           s/^[[:space:]]*Screenshot[[:space:]]+([^[:space:]]+)[[:space:]]*$/\1/p' "$1" \
    | grep -v '^_' || true
}

# True if the artifact looks like a real capture.
#
# GIFs are optimized here rather than in a later pass, because the two jobs are
# the same operation. VHS writes full, undeduplicated frames — raw GIFs run to
# tens of megabytes — and `gifsicle -O3` rewrites only the pixels that change
# between frames (lossless, typically 20-30x smaller, no visible difference).
# A frozen recording is hundreds of *identical* frames, so that same merge
# collapses it to a hollow file: the collapse is exactly how we spot one.
artifact_ok() {
  local f="$1"
  [ -s "$f" ] || return 1

  case "$f" in
    *.gif)
      command -v gifsicle >/dev/null || { [ "$(wc -c < "$f")" -ge 5120 ]; return; }
      gifsicle -O3 --batch "$f" 2>/dev/null || return 1
      local frames
      frames=$(gifsicle --info "$f" 2>/dev/null | grep -c '^[[:space:]]*+ image') || frames=0
      [ "$(wc -c < "$f")" -ge 5120 ] && [ "$frames" -ge 3 ]
      ;;
    *)
      [ "$(wc -c < "$f")" -ge 2048 ]
      ;;
  esac
}

filter="${1:-}"
shopt -s nullglob
rendered=0
MAX_ATTEMPTS=3

for tape in "$TAPE_DIR"/*.tape; do
  name="$(basename "$tape" .tape)"
  [ -n "$filter" ] && [[ "$name" != *"$filter"* ]] && continue

  attempt=1
  while :; do
    if [ "$attempt" -eq 1 ]; then echo "▸ rendering $name"; else echo "▸ rendering $name (attempt $attempt)"; fi
    (cd "$STAGE" && vhs "$tape" >/dev/null)

    bad=""
    while IFS= read -r artifact; do
      [ -n "$artifact" ] || continue
      if ! artifact_ok "$STAGE/$artifact"; then
        bad="$bad $artifact"
        rm -f "$STAGE/$artifact"
      fi
    done < <(expected_artifacts "$tape")

    [ -z "$bad" ] && break

    if [ "$attempt" -ge "$MAX_ATTEMPTS" ]; then
      echo "error: $name produced no usable:$bad (after $MAX_ATTEMPTS attempts)" >&2
      exit 1
    fi
    echo "  retrying — VHS recording came up empty for:$bad"
    attempt=$((attempt + 1))
    sleep 3
  done

  while IFS= read -r artifact; do
    [ -n "$artifact" ] || continue
    printf '  %-24s %5sK\n' "$artifact" "$(( $(wc -c < "$STAGE/$artifact") / 1024 ))"
  done < <(expected_artifacts "$tape")

  rendered=$((rendered + 1))
  sleep 1  # let ttyd fully release before the next capture
done

if [ "$rendered" -eq 0 ]; then
  echo "error: no tapes matched '${filter}'" >&2
  exit 1
fi

command -v gifsicle >/dev/null || \
  echo "warning: gifsicle not found — GIFs left unoptimized (brew install gifsicle)" >&2

# Still tapes emit a throwaway GIF alongside their PNG (VHS always records a
# session); only named artifacts are published.
for artifact in "$STAGE"/*.gif "$STAGE"/*.png; do
  base="$(basename "$artifact")"
  [[ "$base" == _* ]] && continue
  cp "$artifact" "$OUT_DIR/$base"
done

echo "▸ done"
ls -lh "$OUT_DIR"
