export {
  EnhancedSelectInput,
  useEnhancedSelectInput,
  DefaultIndicatorComponent,
  DefaultItemComponent,
  DefaultGroupHeaderComponent,
  DefaultBreadcrumbComponent,
  DefaultSeparatorComponent,
  DefaultLoadingComponent,
  resolveInitialIndex,
  resolveInitialSelection,
  findNextValidIndex,
  findFirstValidIndex,
  findLastValidIndex,
  truncateLabel,
  isSeparator,
  isSelectable,
  matchesQuery,
  computeMatchRanges,
  buildHelpSegments,
  resolveKeyMap,
} from './enhanced-select-input/index.js'

export type {
  Item,
  SeparatorItem,
  ItemOrSeparator,
  KeyMap,
  MatchMode,
  EnhancedSelectInputProps,
  Theme,
  UseEnhancedSelectInputProps,
  UseEnhancedSelectInputResult,
  IndicatorProps,
  ItemProps,
  GroupHeaderProps,
  BreadcrumbProps,
  TruncateMode,
  SeparatorProps,
  LoadingProperties,
  ResolvedKeyMap,
  // Deprecated aliases — kept for backward compatibility, will be removed
  // in a future minor. Prefer the `*Props` names above.
  Properties,
  UseEnhancedSelectInputProperties,
  IndicatorProperties,
  ItemProperties,
  GroupHeaderProperties,
  BreadcrumbProperties,
  SeparatorProperties,
} from './enhanced-select-input/index.js'
